package com.coditria.walletai.app

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLocale { Arabic, English }

/**
 * UI string table — every visible label runs through this so the whole app
 * can switch between Arabic and English when the user toggles the locale
 * in Settings. Mirrors the `TR` map in the HTML prototype.
 */
@Immutable
data class WalletStrings(
    val locale: AppLocale,

    // Splash
    val appName: String,
    val tagline: String,
    val versionLoading: String,

    // Auth shared
    val email: String,
    val password: String,
    val signIn: String,
    val signUp: String,
    val createAccount: String,
    val rememberMe: String,
    val forgotPassword: String,
    val orSignInWith: String,
    val noAccount: String,
    val haveAccount: String,
    val welcomeBack: String,
    val welcomeBackSub: String,
    val createTitle: String,
    val createSub: String,
    val firstName: String,
    val lastName: String,
    val mobile: String,
    val passwordPlaceholder: String,
    val passwordStrength: String,
    val agreeTerms: String,

    // Dashboard
    val goodMorning: String,
    val totalBalance: String,
    val netThisMonth: (String, String) -> String,
    val income: String,
    val expenses: String,
    val add: String,
    val voice: String,
    val transfer: String,
    val goals: String,
    val analysis: String,
    val more: String,
    val viewAll: String,
    val week: String,
    val month: String,
    val year: String,
    val upcomingInstallments: String,
    val recentTransactions: String,

    // Add transaction
    val newTransaction: String,
    val expense: String,
    val transactionType: String,
    val tellMeAboutTx: String,
    val aiUnderstanding: String,
    val amount: String,
    val ai: String,
    val autoSuggestions: String,
    val category: String,
    val date: String,
    val account: String,
    val cancel: String,
    val saveTransaction: String,

    // Voice
    val voiceAssistant: String,
    val listening: String,
    val sayInArabic: String,
    val live: String,
    val transcribing: String,

    // Installments
    val installments: String,
    val totalRemainingDebt: String,
    val monthly: String,
    val remaining: String,
    val tabActive: String,
    val tabCalendar: String,
    val tabDone: String,
    val pressureMap: String,
    val perMonth: String,

    // Reports
    val reports: String,
    val financialHealth: String,
    val verdictGood: String,
    val outOf: (Int) -> String,
    val expenseBreakdown: String,
    val smartInsights: String,
    val expensesUnit: String,

    // Settings
    val settings: String,
    val accountSection: String,
    val profile: String,
    val profileSub: String,
    val accountsCards: String,
    val linkedAccounts: (Int) -> String,
    val limitsBudgets: String,
    val setMonthlyBudget: String,
    val preferences: String,
    val appearance: String,
    val appearanceSub: String,
    val light: String,
    val dark: String,
    val language: String,
    val languageSub: String,
    val arabic: String,
    val english: String,
    val currency: String,
    val egyptianPound: String,
    val notifications: String,
    val notificationsSub: String,
    val securityPrivacy: String,
    val changePassword: String,
    val changePasswordSub: String,
    val biometrics: String,
    val biometricsSub: String,
    val twoFactor: String,
    val twoFactorSub: String,
    val support: String,
    val helpCenter: String,
    val termsPrivacy: String,
    val signOut: String,
    val versionLine: String,
    val proMembership: String,

    // Bottom nav
    val navHome: String,
    val navTransactions: String,
    val navReports: String,
    val navSettings: String,
)

val ArabicStrings = WalletStrings(
    locale = AppLocale.Arabic,
    appName = "WalletAI",
    tagline = "محفظتك الذكية · مدعومة بالـ AI",
    versionLoading = "v 2.4.0 · جاري التحميل…",
    email = "البريد الإلكتروني",
    password = "كلمة السر",
    signIn = "تسجيل الدخول",
    signUp = "أنشئ حساب",
    createAccount = "إنشاء الحساب",
    rememberMe = "تذكرني",
    forgotPassword = "نسيت كلمة السر؟",
    orSignInWith = "أو سجّل بـ",
    noAccount = "ليس عندك حساب؟",
    haveAccount = "عندك حساب بالفعل؟",
    welcomeBack = "أهلاً بعودتك 👋",
    welcomeBackSub = "سجّل دخولك عشان تكمّل إدارة أموالك بذكاء",
    createTitle = "أنشئ حسابك",
    createSub = "دقيقة واحدة وتبدأ تتحكم في فلوسك",
    firstName = "الاسم الأول",
    lastName = "اسم العائلة",
    mobile = "رقم الموبايل",
    passwordPlaceholder = "على الأقل 8 أحرف",
    passwordStrength = "قوة جيدة · أضف رمز خاص لتقويتها",
    agreeTerms = "أوافق على الشروط والأحكام و سياسة الخصوصية",
    goodMorning = "صباح الخير 👋",
    totalBalance = "الرصيد الكلي",
    netThisMonth = { amt, cur -> "+$amt $cur صافي هذا الشهر" },
    income = "الدخل",
    expenses = "المصاريف",
    add = "إضافة",
    voice = "صوتي",
    transfer = "تحويل",
    goals = "أهداف",
    analysis = "التحليل",
    more = "المزيد ‹",
    viewAll = "الكل ‹",
    week = "أسبوع",
    month = "شهر",
    year = "سنة",
    upcomingInstallments = "أقساط قريبة",
    recentTransactions = "آخر المعاملات",
    newTransaction = "معاملة جديدة",
    expense = "مصروف",
    transactionType = "تحويل",
    tellMeAboutTx = "قول كده عن المعاملة",
    aiUnderstanding = "AI · فهم النص",
    amount = "المبلغ",
    ai = "AI",
    autoSuggestions = "اقتراحات تلقائية",
    category = "الفئة",
    date = "التاريخ",
    account = "الحساب",
    cancel = "إلغاء",
    saveTransaction = "حفظ المعاملة",
    voiceAssistant = "المساعد الصوتي",
    listening = "جاري الاستماع",
    sayInArabic = "قول معاملتك بالعربي",
    live = "مباشر",
    transcribing = "جاري التحويل لنص",
    installments = "الأقساط",
    totalRemainingDebt = "إجمالي الديون المتبقية",
    monthly = "شهري",
    remaining = "متبقي",
    tabActive = "نشطة",
    tabCalendar = "التقويم",
    tabDone = "منتهية",
    pressureMap = "خريطة الضغط الشهري",
    perMonth = "/شهر",
    reports = "التقارير",
    financialHealth = "صحتك المالية",
    verdictGood = "جيد",
    outOf = { max -> "من $max" },
    expenseBreakdown = "توزيع المصاريف",
    smartInsights = "تحليلات وملاحظات ذكية",
    expensesUnit = "ج.م مصاريف",
    settings = "الإعدادات",
    accountSection = "الحساب",
    profile = "الملف الشخصي",
    profileSub = "عدّل اسمك وصورتك",
    accountsCards = "الحسابات والبطاقات",
    linkedAccounts = { n -> "$n حسابات مرتبطة" },
    limitsBudgets = "الحدود والميزانيات",
    setMonthlyBudget = "حدد ميزانية شهرية",
    preferences = "التفضيلات",
    appearance = "المظهر",
    appearanceSub = "فاتح أو داكن",
    light = "فاتح",
    dark = "داكن",
    language = "اللغة",
    languageSub = "العربية أو الإنجليزية",
    arabic = "العربية",
    english = "English",
    currency = "العملة",
    egyptianPound = "الجنيه المصري",
    notifications = "الإشعارات",
    notificationsSub = "تنبيهات الأقساط والمصاريف",
    securityPrivacy = "الأمان والخصوصية",
    changePassword = "تغيير كلمة السر",
    changePasswordSub = "آخر تحديث منذ 3 أشهر",
    biometrics = "البصمة / Face ID",
    biometricsSub = "دخول سريع وآمن",
    twoFactor = "المصادقة الثنائية",
    twoFactorSub = "طبقة حماية إضافية",
    support = "الدعم",
    helpCenter = "مركز المساعدة",
    termsPrivacy = "الشروط والخصوصية",
    signOut = "تسجيل الخروج",
    versionLine = "WalletAI · v 2.4.0",
    proMembership = "عضوية Pro",
    navHome = "الرئيسية",
    navTransactions = "المعاملات",
    navReports = "التقارير",
    navSettings = "الإعدادات",
)

val EnglishStrings = WalletStrings(
    locale = AppLocale.English,
    appName = "WalletAI",
    tagline = "Your smart wallet · powered by AI",
    versionLoading = "v 2.4.0 · Loading…",
    email = "Email",
    password = "Password",
    signIn = "Sign in",
    signUp = "Sign up",
    createAccount = "Create account",
    rememberMe = "Remember me",
    forgotPassword = "Forgot password?",
    orSignInWith = "Or sign in with",
    noAccount = "Don't have an account?",
    haveAccount = "Already have an account?",
    welcomeBack = "Welcome back 👋",
    welcomeBackSub = "Sign in to keep managing your money smartly",
    createTitle = "Create your account",
    createSub = "One minute and you're in control of your money",
    firstName = "First name",
    lastName = "Last name",
    mobile = "Mobile number",
    passwordPlaceholder = "At least 8 characters",
    passwordStrength = "Good strength · add a symbol to make it stronger",
    agreeTerms = "I agree to the Terms & Conditions and Privacy Policy",
    goodMorning = "Good morning 👋",
    totalBalance = "Total balance",
    netThisMonth = { amt, cur -> "+$amt $cur net this month" },
    income = "Income",
    expenses = "Expenses",
    add = "Add",
    voice = "Voice",
    transfer = "Transfer",
    goals = "Goals",
    analysis = "Analysis",
    more = "More ‹",
    viewAll = "View all ‹",
    week = "Week",
    month = "Month",
    year = "Year",
    upcomingInstallments = "Upcoming installments",
    recentTransactions = "Latest transactions",
    newTransaction = "New transaction",
    expense = "Expense",
    transactionType = "Transfer",
    tellMeAboutTx = "Tell me about the transaction",
    aiUnderstanding = "AI · text understanding",
    amount = "Amount",
    ai = "AI",
    autoSuggestions = "Auto suggestions",
    category = "Category",
    date = "Date",
    account = "Account",
    cancel = "Cancel",
    saveTransaction = "Save transaction",
    voiceAssistant = "Voice assistant",
    listening = "Listening",
    sayInArabic = "Say your transaction",
    live = "Live",
    transcribing = "Transcribing",
    installments = "Installments",
    totalRemainingDebt = "Total remaining debt",
    monthly = "Monthly",
    remaining = "Remaining",
    tabActive = "Active",
    tabCalendar = "Calendar",
    tabDone = "Done",
    pressureMap = "Monthly pressure map",
    perMonth = "/mo",
    reports = "Reports",
    financialHealth = "Financial health",
    verdictGood = "Good",
    outOf = { max -> "out of $max" },
    expenseBreakdown = "Expense breakdown",
    smartInsights = "Smart insights & notes",
    expensesUnit = "EGP spent",
    settings = "Settings",
    accountSection = "Account",
    profile = "Profile",
    profileSub = "Edit your name & photo",
    accountsCards = "Accounts & cards",
    linkedAccounts = { n -> "$n linked accounts" },
    limitsBudgets = "Limits & budgets",
    setMonthlyBudget = "Set a monthly budget",
    preferences = "Preferences",
    appearance = "Appearance",
    appearanceSub = "Light or dark",
    light = "Light",
    dark = "Dark",
    language = "Language",
    languageSub = "Arabic or English",
    arabic = "العربية",
    english = "English",
    currency = "Currency",
    egyptianPound = "Egyptian Pound",
    notifications = "Notifications",
    notificationsSub = "Bill & spending alerts",
    securityPrivacy = "Security & privacy",
    changePassword = "Change password",
    changePasswordSub = "Last updated 3 months ago",
    biometrics = "Fingerprint / Face ID",
    biometricsSub = "Fast and secure sign-in",
    twoFactor = "Two-factor authentication",
    twoFactorSub = "Extra layer of protection",
    support = "Support",
    helpCenter = "Help center",
    termsPrivacy = "Terms & Privacy",
    signOut = "Log out",
    versionLine = "WalletAI · v 2.4.0",
    proMembership = "Pro membership",
    navHome = "Home",
    navTransactions = "Transactions",
    navReports = "Reports",
    navSettings = "Settings",
)

fun stringsFor(locale: AppLocale): WalletStrings = when (locale) {
    AppLocale.Arabic -> ArabicStrings
    AppLocale.English -> EnglishStrings
}

val LocalWalletStrings = staticCompositionLocalOf { ArabicStrings }
