package com.coditria.walletai.data.db

import app.cash.sqldelight.db.SqlDriver
import app.cash.sqldelight.driver.native.NativeSqliteDriver

/**
 * iOS driver — backed by [NativeSqliteDriver]. The schema is owned by
 * [WalletDatabase] (generated by SQLDelight from the .sq files).
 */
actual class DatabaseDriverFactory {
    actual fun create(): SqlDriver = NativeSqliteDriver(
        schema = WalletDatabase.Schema,
        name = DATABASE_FILE_NAME,
    )
}
